Repository QingQiz/NMSqL, pull requests merged in 2020-11, with the labels that each got.

#11 Compiler：表达式的代码生成写完了
  src/frontend/compiler/.gitignore
  src/frontend/compiler/Makefile
  src/frontend/compiler/README.md
  src/frontend/compiler/Test.hs
  src/frontend/compiler/hie.yaml
  src/frontend/compiler/package.yaml
  src/frontend/compiler/src/CodeGenerator/CodeGenerator.hs
  src/frontend/compiler/src/CodeGenerator/CodeGeneratorUtils.hs
  src/frontend/compiler/src/CodeGenerator/Expr.hs
  src/frontend/compiler/src/CodeGenerator/Instruction.hs
  src/frontend/compiler/src/FFI/FFI.hs
  src/frontend/compiler/src/FFI/FFIStructure.hs
  src/frontend/compiler/src/Parser/Ast.hs
  src/frontend/compiler/src/Parser/Parser.hs
  src/frontend/compiler/src/Test/Main.hs
  src/frontend/compiler/src/Test/TestCodeGenerator.hs
  src/frontend/compiler/src/Test/TestUtils.hs
  src/frontend/compiler/stack.yaml
Labels: enhancement

#18 fix: compiler: 修复了 between-expr，使用 Set 指令简化了 IR
  src/frontend/compiler/src/CodeGenerator/Expr.hs
  src/frontend/compiler/src/CodeGenerator/Instruction.hs
  src/frontend/compiler/src/Test/TestCodeGenerator.hs
Labels: bug, enhancement

#31 add transaction interface
  doc/backend/VM.md
  src/backend/include/DbEngineInterface.h
Labels: documentation, enhancement

#28 fix bugs in IR doc
  doc/IR.md
Labels: bug, documentation

#37 change statement in IR
  doc/IR.md
Labels: documentation

#43 add SortSetDesc IR
  doc/IR.md
Labels: documentation, enhancement

#45 add IR SetOpen
  doc/IR.md
Labels: documentation

#46 修改IR rewind的表述 删除IR fcnt
  doc/IR.md
Labels: documentation, enhancement

#53 add `extern "C"` to DbEngineInterface.h
  src/backend/include/DbEngineInterface.h
  src/backend/include/VMInterface.h
Labels: bug

#52 dbengine add interface setCookies
  src/backend/include/DbEngineInterface.h
Labels: bug, documentation
